// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT39tdNTOx7RP2TmP2p1iE2d3p4KIxHGU',
    appId: '1:683198013079:web:ce9844d9d48cbe3707d3d2',
    messagingSenderId: '683198013079',
    projectId: 'anubis-baf99',
    authDomain: 'anubis-baf99.firebaseapp.com',
    storageBucket: 'anubis-baf99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIl16lUKTyQxUOajHTC78-ZtxklKcgwrQ',
    appId: '1:683198013079:android:35b49c0ff390c9ea07d3d2',
    messagingSenderId: '683198013079',
    projectId: 'anubis-baf99',
    storageBucket: 'anubis-baf99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocfvsWr0vgsnPLVStrMasW9a-iZE4s9g',
    appId: '1:683198013079:ios:c6e40524589a9ffd07d3d2',
    messagingSenderId: '683198013079',
    projectId: 'anubis-baf99',
    storageBucket: 'anubis-baf99.firebasestorage.app',
    androidClientId:
        '683198013079-g23tdf9ccadk90mea4oobhfcfhaen7gv.apps.googleusercontent.com',
    iosClientId:
        '683198013079-0limngtvs63evsh728vf5shuflu7tre8.apps.googleusercontent.com',
    iosBundleId: 'com.mutoServices.mutoClientApp',
  );
}
